// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/SearchResult/children/album.vue')['default']
    ColorPicker: typeof import('./src/components/utils/ColorPicker.vue')['default']
    Comment: typeof import('./src/components/musicItem/Comment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FindMusicBanner: typeof import('./src/components/musicItem/FindMusicBanner.vue')['default']
    HotSearchDetail: typeof import('./src/components/HotSearchDetail.vue')['default']
    Lyric: typeof import('./src/components/SearchResult/children/lyric.vue')['default']
    PlayAllAndDownloadAll: typeof import('./src/components/utils/PlayAllAndDownloadAll.vue')['default']
    PlayList: typeof import('./src/components/musicItem/PlayList.vue')['default']
    Podcast: typeof import('./src/components/SearchResult/children/podcast.vue')['default']
    Recommend: typeof import('./src/components/musicItem/Recommend.vue')['default']
    RecommendItem: typeof import('./src/components/musicItem/RecommendItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult/SearchResult.vue')['default']
    Singer: typeof import('./src/components/SearchResult/children/singer.vue')['default']
    Single: typeof import('./src/components/SearchResult/children/single.vue')['default']
    SongList: typeof import('./src/components/SearchResult/children/songList.vue')['default']
    SongPlayList: typeof import('./src/components/musicItem/SongPlayList.vue')['default']
    Subscribers: typeof import('./src/components/musicItem/Subscribers.vue')['default']
    User: typeof import('./src/components/SearchResult/children/user.vue')['default']
    UserSetting: typeof import('./src/components/UserSetting.vue')['default']
    Video: typeof import('./src/components/SearchResult/children/video.vue')['default']
    Voice: typeof import('./src/components/SearchResult/children/voice.vue')['default']
  }
}
