// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HotSearch: typeof import('./src/components/hotSearch.vue')['default']
    HotSearchDetail: typeof import('./src/components/HotSearchDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
  }
}
