// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/SearchResult/children/album.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HotSearch: typeof import('./src/components/hotSearch.vue')['default']
    HotSearchDetail: typeof import('./src/components/HotSearchDetail.vue')['default']
    Lyric: typeof import('./src/components/SearchResult/children/lyric.vue')['default']
    Pagination: typeof import('./src/components/utils/Pagination.vue')['default']
    Podcast: typeof import('./src/components/SearchResult/children/podcast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult/SearchResult.vue')['default']
    Singer: typeof import('./src/components/SearchResult/children/singer.vue')['default']
    Single: typeof import('./src/components/SearchResult/children/single.vue')['default']
    SongList: typeof import('./src/components/SearchResult/children/songList.vue')['default']
    User: typeof import('./src/components/SearchResult/children/user.vue')['default']
    Video: typeof import('./src/components/SearchResult/children/video.vue')['default']
    Voice: typeof import('./src/components/SearchResult/children/voice.vue')['default']
  }
}
